# robotpkg Makefile for:	planning/libhatp
# Created:			Raphaël Lallement, 18/01/2013
#

DISTNAME=		libhatp-${VERSION}
VERSION=		1.0.0
PKGREVISION=
CATEGORIES=		planning
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=libhatp/}
MASTER_REPOSITORY=	${MASTER_REPOSITORY_OPENROBOTS}libhatp


MAINTAINER=		raphael.lallement@laas.fr
COMMENT=		Library to handle HATP plans
LICENSE=		2-clause-bsd

MAKE_JOBS_SAFE=		yes

include ../../mk/sysdep/cmake.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
