# robotpkg Makefile for:	graphics/ros-rviz
# Created:			Charles Lesire on Tue, 08 March 2014
#

ROS_PKG=	rviz
ROS_VERSION=	1.9.35
ROS_REPO=	ros-visualization

CATEGORIES=	graphics
ROS_COMMENT=	3D robot vizualizer

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../wip/ros-laser-geometry/depend.mk
include ../../graphics/ros-python-qt-binding/depend.mk
include ../../graphics/urdfdom/depend.mk
include ../../wip/ros-interactive-markers/depend.mk
#  <build_depend>libqt4-dev</build_depend>
#  <build_depend>libqt4-opengl-dev</build_depend>
#  <build_depend>libogre-dev</build_depend>
include ../../devel/yaml-cpp/depend.mk
include ../../graphics/assimp/depend.mk
include ../../math/eigen3/depend.mk
include ../../mk/robotpkg.mk
