# robotpkg Makefile for:	devel/catkin
# Created:			Anthony Mallet on Sun, 15 Jul 2012
#

ROS_PKG=		ros
ROS_VERSION=		1.8.10
PKGNAME=		ros-core-${ROS_VERSION}

CATEGORIES=		devel
ROS_COMMENT=		core
HOMEPAGE=		http://www.ros.org/wiki/ROS

include ../../wip/ros18-base/Makefile.common

include ../../archivers/bzip2/depend.mk
include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk
include ../../wip/catkin/depend.mk
include ../../wip/rospack/depend.mk
include ../../wip/py-rospkg/depend.mk
include ../../mk/sysdep/python.mk
include ../../mk/sysdep/py-nose.mk
include ../../mk/robotpkg.mk
