# robotpkg Makefile for:	interface/ros-std-msgs
# Created:			Anthony Mallet on Mon,  8 Oct 2012
#

ROS_PKG=		std-msgs
ROS_VERSION=		0.4.11

CATEGORIES=		interface
ROS_COMMENT=		standard messages definition
HOMEPAGE=		http://www.ros.org/wiki/std_msgs

include ../../wip/ros18-base/Makefile.common

include ../../pkgtools/pkg-config/depend.mk
include ../../wip/catkin/depend.mk
include ../../wip/ros-genmsg/depend.mk
include ../../wip/ros-langs/depend.mk
include ../../mk/sysdep/python.mk
include ../../mk/robotpkg.mk
