# robotpkg Makefile for:	interface/ros-genlisp
# Created:			Anthony Mallet on Mon,  8 Oct 2012
#

ROS_PKG=		genlisp
ROS_VERSION=		0.3.3
PKGNAME=		ros-genlisp-${ROS_VERSION}

CATEGORIES=		interface
ROS_COMMENT=		lisp code generator for ROS .msg format
HOMEPAGE=		http://www.ros.org/wiki/roslisp
MAINTAINER=		mallet@laas.fr
LICENSE=		modified-bsd

include ../../wip/ros18-base/Makefile.common

include ../../wip/catkin/depend.mk
include ../../wip/ros-genmsg/depend.mk
include ../../mk/sysdep/python.mk
include ../../mk/robotpkg.mk
