# robotpkg Makefile for:	interface/ros-common-msgs
# Created:			Anthony Mallet on Tue,  9 Oct 2012
#

ROS_PKG=		common-msgs
ROS_VERSION=		1.8.13

CATEGORIES=		interface
ROS_COMMENT=		common messages definition
HOMEPAGE=		http://www.ros.org/wiki/common_msgs

include ../../wip/ros18-base/Makefile.common

include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk
include ../../wip/catkin/depend.mk
include ../../wip/ros-genmsg/depend.mk
include ../../wip/ros-langs/depend.mk
include ../../wip/ros-std-msgs/depend.mk
include ../../mk/sysdep/python.mk
include ../../mk/robotpkg.mk
