# robotpkg Makefile for:	doc/demo-genom3
# Created:			Anthony Mallet on Fri, 17 May 2013
#

DISTNAME=		demo-genom3-1.2
CATEGORIES=		doc
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=demo/}
MASTER_REPOSITORY=	${MASTER_REPOSITORY_OPENROBOTS_TRAC}demo-genom
CHECKOUT_OPTS=		-r genom3

MAINTAINER=		openrobots@laas.fr
COMMENT=		sample GenoM module used in the tutorial
LICENSE=		isc

include ../../wip/genom3/module.mk

include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
