# robotpkg Makefile for:	manipulation/pqp-libs
# Created:			Severin Lemaignan on Tue, 31 Aug 2010
#

#THIS PACKAGE SHOULD BE REWORKED TO USE THE ORIGINAL LIBRARY FROM UNIVERSITY
# OF NORTH CAROLINA
DISTNAME=		pqp-libs-1.1
CATEGORIES=		manipulation
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=pqp-libs/}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/pqp-libs

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		http://gamma.cs.unc.edu/SSV/
COMMENT=		A Proximity Query Package

#The PQP license is an open-source BSD-like license "for research purpose only"...
#LICENSE=		pqp-license

USE_LANGUAGES+=		c c++

GNU_CONFIGURE=		yes

include ../../mk/robotpkg.mk
