# robotpkg Makefile for:	devel/catkin
# Created:			Anthony Mallet on Sun, 15 Jul 2012
#

ROS_PKG=		roscpp-core
ROS_VERSION=		0.2.6

CATEGORIES=		devel
ROS_COMMENT=		underlying data libraries for roscpp messages
HOMEPAGE=		http://www.ros.org/
MAINTAINER=		mallet@laas.fr
LICENSE=		modified-bsd

include ../../wip/ros18-base/Makefile.common

include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk
include ../../wip/catkin/depend.mk
include ../../wip/ros-core/depend.mk
include ../../mk/robotpkg.mk
