# robotpkg Makefile for:	robots/romeo-description
# Created:			Aurélie Clodic on Wed, 11 Jun 2014
#
VERSION=		0.3.0
DISTNAME=		romeo_description-${VERSION}
PKGNAME=		romeo-description-${VERSION}
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=romeo/}
MASTER_REPOSITORY=	${MASTER_REPOSITORY_GITHUB}laas/romeo

CATEGORIES=		robots
COMMENT=		ROS Aldebaran Robotics Romeo robot model description
# (model copyright hold by Aldebaran Robotics) 
LICENSE=		2-clause-bsd
MAINTAINER=		hpp@laas.fr

include ../../devel/ros-catkin/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/sysdep/doxygen.mk
include ../../mk/sysdep/graphviz.mk
include ../../mk/sysdep/pdflatex.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
