# $LAAS: Makefile 2010/03/22 16:02:45 nksallem $
#
# Copyright (c) 2007-2010 LAAS/CNRS
# All rights reserved.
#
# Redistribution and use  in source  and binary  forms,  with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   1. Redistributions of  source  code must retain the  above copyright
#      notice and this list of conditions.
#   2. Redistributions in binary form must reproduce the above copyright
#      notice and  this list of  conditions in the  documentation and/or
#      other materials provided with the distribution.
#
#                                      	 Nizar Sallem on Tue Aug 24 2010
#

DISTNAME=			liblbfgs-1.9
PKGNAME=			liblbfgs
EXTRACT_SUFX= .tar.gz
CATEGORIES=		math
MASTER_SITES=	http://www.chokkan.org/software/dist/

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=			http://www.chokkan.org/software/liblbfgs/
COMMENT=			Limited-memory Broyden-Fletcher-Goldfarb-Shanno C port
LICENSE=			mit

USE_LANGUAGES+=		c c++

GNU_CONFIGURE = yes

include ../../pkgtools/libtool/depend.mk
include ../../mk/robotpkg.mk
