# robotpkg Makefile for:	graphics/ros-interactive-markers
# Created:			Charles Lesire on Tue, 08 March 2014
#

ROS_PKG=	interactive_markers
ROS_VERSION=	1.9.9
ROS_REPO=	ros-visualization

CATEGORIES=	graphics
ROS_COMMENT=	interactive marker library for RViz and similar visualizers.

include ../../meta-pkgs/ros-base/Makefile.common

include ../../sysutils/ros-console-bridge/depend.mk
include ../../lang/ros-gencpp/depend.mk
include ../../devel/ros-roscpp-core/depend.mk
include ../../lang/ros-genpy/depend.mk
include ../../interfaces/ros-std-msgs/depend.mk
include ../../math/ros-geometry/depend.mk
include ../../interfaces/ros-common-msgs/depend.mk

include ../../devel/ros-catkin/depend.mk
include ../../mk/robotpkg.mk
