# robotpkg Makefile for:	devel/catkin
# Created:			Anthony Mallet on Sun, 15 Jul 2012
#

ROS_PKG=		rospack
ROS_VERSION=		2.0.13

CATEGORIES=		devel
ROS_COMMENT=		command-line tool for retriving package information
HOMEPAGE=		http://www.ros.org/wiki/rospack
MAINTAINER=		mallet@laas.fr
LICENSE=		modified-bsd

include ../../wip/ros18-base/Makefile.common

include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk
include ../../wip/catkin/depend.mk
include ../../mk/sysdep/python.mk
include ../../mk/sysdep/py-nose.mk
include ../../mk/sysdep/googletest.mk
include ../../mk/robotpkg.mk
