# robotpkg Makefile for:	interface/ros-genmsg
# Created:			Anthony Mallet on Mon,  8 Oct 2012
#

ROS_PKG=		genmsg
ROS_VERSION=		0.3.10
PKGNAME=		ros-genmsg-${ROS_VERSION}

CATEGORIES=		interface
ROS_COMMENT=		code generator for ROS .msg format
HOMEPAGE=		http://www.ros.org/wiki/genmsg
MAINTAINER=		mallet@laas.fr
LICENSE=		modified-bsd

include ../../wip/ros18-base/Makefile.common

include ../../wip/catkin/depend.mk
include ../../mk/sysdep/python.mk
include ../../mk/robotpkg.mk
