# robotpkg Makefile for:	interface/ros-genmsg
# Created:			Anthony Mallet on Mon,  8 Oct 2012
#

ROS_PKG=		genmsg
ROS_VERSION=		0.3.10

CATEGORIES=		interface
ROS_COMMENT=		code generator for ROS .msg format
HOMEPAGE=		http://www.ros.org/wiki/genmsg

include ../../wip/ros18-base/Makefile.common

include ../../wip/catkin/depend.mk
include ../../mk/robotpkg.mk
