# robotpkg Makefile for:	motion/visuserv-genom
# Created:			N. OUADAH and A. Mekonnen on 28/02/11
#

DISTNAME=		visuserv-genom-1.0
CATEGORIES=		motion
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=visuserv-genom/}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/visuserv-genom

MAINTAINER=		openrobots@laas.fr
COMMENT=		Genom module for visual servoing & Multimodal person following
LICENSE=		gnu-lgpl-v3


GENOM_MODULE=		visuserv

include ../../architecture/genom/depend.mk
include ../../localization/pom-genom/depend.mk
include ../../interfaces/genPos-genom/depend.mk
include ../../hardware/platine-genom/depend.mk
include ../../robots/rflex-genom/depend.mk
include ../../wip/icu-genom/depend.mk
include ../../math/meschach/depend.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
