# robotpkg Makefile for:	hardware/rfid-genom
# Created:			Xavier Broquere on Wed, 27 Oct 2010
#

DISTNAME=		rfid-genom-1.1
CATEGORIES=		hardware
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=rfid-genom/}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/rfid-genom

MAINTAINER=		openrobots@laas.fr
COMMENT=		Genom module for the RFID system
LICENSE=		gnu-lgpl-v3


GENOM_MODULE=		rfid

include ../../architecture/genom/depend.mk
include ../../localization/pom-genom/depend.mk
include ../../interfaces/genBasic-genom/depend.mk
include ../../hardware/platine-genom/depend.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
