# robotpkg Makefile for:	devel/catkin
# Created:			Anthony Mallet on Sun, 15 Jul 2012
#

ROS_PKG=		langs
ROS_VERSION=		0.3.5

CATEGORIES=		interface
ROS_COMMENT=		meta package for language bindings of messages
HOMEPAGE=		http://www.ros.org

include ../../wip/ros18-base/Makefile.common

include ../../wip/catkin/depend.mk
include ../../wip/roscpp-core/depend.mk
include ../../wip/ros-langs-dev/depend.mk
include ../../mk/sysdep/python.mk
include ../../mk/robotpkg.mk
