# robotpkg Makefile for:	middleware/ros-comm
# Created:			Anthony Mallet on Tue,  9 Oct 2012
#

ROS_PKG=		rx
ROS_VERSION=		1.8.9

CATEGORIES=		graphics
ROS_COMMENT=		GUI tools
HOMEPAGE=		http://www.ros.org/wiki/rx

include ../../wip/ros18-base/Makefile.common

SUBST_CLASSES+=		py-distsetup

include ../../wip/catkin/depend.mk
include ../../wip/ros-comm/depend.mk
include ../../wip/ros-core/depend.mk
include ../../wip/ros-std-msgs/depend.mk
include ../../wip/rospack/depend.mk
include ../../mk/sysdep/graphviz.mk
include ../../mk/sysdep/py-matplotlib.mk
include ../../mk/sysdep/py-wxpython.mk
include ../../mk/sysdep/wxwidgets.mk
include ../../mk/robotpkg.mk
