# robotpkg Makefile for:	manipulation/kukaFri-libs
# Created:			Severin Lemaignan on Tue, 31 Aug 2010
#

DISTNAME=		kukaFri-libs-1.2
CATEGORIES=		manipulation
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=kukaFri-libs/}
# TODO: properly add an interactive fetch

MAINTAINER=		xavier.broquere@laas.fr
COMMENT=		KuKa low-level libraries for their arm
LICENSE=		kuka-license

USE_LANGUAGES+=		c c++

include ../../mk/sysdep/cmake.mk
include ../../mk/robotpkg.mk
