# robotpkg Makefile for:	interface/ros-genpy
# Created:			Anthony Mallet on Mon,  8 Oct 2012
#

ROS_PKG=		genpy
ROS_VERSION=		0.3.7

CATEGORIES=		interface
ROS_COMMENT=		python code generator for ROS .msg format
HOMEPAGE=		http://www.ros.org/wiki/genpy

include ../../wip/ros18-base/Makefile.common

include ../../wip/catkin/depend.mk
include ../../wip/ros-genmsg/depend.mk
include ../../mk/sysdep/python.mk
include ../../mk/robotpkg.mk
