# robotpkg Makefile for:	middleware/ros-actionlib
# Created:			Anthony Mallet on Tue, 9 Oct 2012
#

ROS_PKG=		actionlib
ROS_VERSION=		1.8.7

CATEGORIES=		middleware
ROS_COMMENT=		standardized interface for preemptable tasks
HOMEPAGE=		http://www.ros.org/wiki/actionlib

include ../../wip/ros18-base/Makefile.common

SUBST_CLASSES+=		py-distsetup

include ../../wip/catkin/depend.mk
include ../../wip/ros-common-msgs/depend.mk
include ../../wip/ros-std-msgs/depend.mk
include ../../wip/ros-genmsg/depend.mk
include ../../wip/ros-langs/depend.mk
include ../../wip/ros-core/depend.mk
include ../../wip/ros-comm/depend.mk
include ../../mk/robotpkg.mk
