# robotpkg Makefile for:	interface/ros-gencpp
# Created:			Anthony Mallet on Mon,  8 Oct 2012
#

ROS_PKG=		gencpp
ROS_VERSION=		0.3.4

CATEGORIES=		interface
ROS_COMMENT=		C++ code generator for ROS .msg format
HOMEPAGE=		http://www.ros.org/wiki/roscpp

include ../../wip/ros18-base/Makefile.common

include ../../wip/catkin/depend.mk
include ../../wip/ros-genmsg/depend.mk
include ../../mk/sysdep/python.mk
include ../../mk/robotpkg.mk
