# robotpkg Makefile for:	image/icu-genom
# Created:			N. Ouadah & A Mekonnen 15 12 2010
#

DISTNAME=		icu-genom-1.0
CATEGORIES=		image
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=icu-genom/}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/icu-genom

MAINTAINER=		openrobots@laas.fr
COMMENT=		Genom module for the icu: user detection and tracking
LICENSE=		gnu-lgpl-v3


GENOM_MODULE=		icu

include ../../architecture/genom/depend.mk
include ../../localization/pom-genom/depend.mk
include ../../interfaces/genBasic-genom/depend.mk
include ../../hardware/platine-genom/depend.mk
include ../../wip/rfid-genom/depend.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
