# Created:		Akin Sisbot Oct 17, 2010
#

DISTNAME=		sparkyarp-genom-0.4
CATEGORIES=		knowledge
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=sparkyarp-genom/}
MASTER_REPOSITORY=	git http://trac.laas.fr/git/robots/sparkyarp-genom

MAINTAINER=		easisbot@laas.fr
COMMENT=		Yarp bridge to SPARK for Chris Project

LICENSE=		gnu-gpl-v2


USE_LANGUAGES+=		c c++

#######################
#### SPARKYARP OPTIONS ####
#######################


#####################

GENOM_MODULE=		sparkyarp

include ../../wip/spark-genom/depend.mk
include ../../architecture/genBasic-genom/depend.mk
include ../../architecture/yarp/depend.mk
include ../../architecture/genom/depend.mk
include ../../mk/robotpkg.mk
