# robotpkg Makefile for:	devel/catkin
# Created:			Anthony Mallet on Sun, 15 Jul 2012
#

ROS_PKG=		langs-dev
ROS_VERSION=		0.1.3

CATEGORIES=		interface
ROS_COMMENT=		meta package for language bindings of messages
HOMEPAGE=		http://www.ros.org

include ../../wip/ros18-base/Makefile.common

include ../../wip/catkin/depend.mk
include ../../wip/ros-gencpp/depend.mk
include ../../wip/ros-genpy/depend.mk
include ../../wip/ros-genlisp/depend.mk
include ../../mk/robotpkg.mk
