# $LAAS: depend.mk 2010/21/04 15:59:08 tmoulard $
#
# Copyright (c) 2010 LAAS/CNRS
# All rights reserved.
#
# Redistribution and use  in source  and binary  forms,  with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   1. Redistributions of  source  code must retain the  above copyright
#      notice and this list of conditions.
#   2. Redistributions in binary form must reproduce the above copyright
#      notice and  this list of  conditions in the  documentation and/or
#      other materials provided with the distribution.
#
#                                      Thomas Moulard on Wed Apr 21 2010
#

HPP_PACKAGE=	hpp-util
VERSION=	0.1
CATEGORIES=	devel
COMMENT=	Technical tools shared amongst HPP.

include ../../wip/hpp/Makefile.common
include ../../mk/robotpkg.mk
