# robotpkg Makefile for:	hardware/joystick-genom
# Created:			Xavier Broquere on 06 Jan 2011
#

DISTNAME=		joystick-genom-1.0
CATEGORIES=		hardware
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=joystick-genom/}
MASTER_REPOSITORY=	${MASTER_REPOSITORY_OPENROBOTS}joystick-genom

MAINTAINER=		xavier.broquere@laas.fr
COMMENT=		Genom module for the Logitech Cordless RumblePad 2 joystick.
LICENSE=		gnu-lgpl-v3

GENOM_MODULE=		joystick


include ../../architecture/genom/depend.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
